# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cols', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('mines', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
